# complete SDF-SRN
_parent_: options/pascal3d/implicit.yaml

group: sdf_srn_pascal3d
name: car
load: output/pretrain/pascal3d/latest.ckpt

arch:
    enc_network: resnet18
    enc_pretrained: true

data:
    dataset: pascal3d
    num_workers: 4
    augment:
        crop_scale: 0.2
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
        hue: 0.5
        rotate:
    bgcolor: 1
    pascal3d:
        set: imagenet
        cat: car

impl:
    sdf_samples: 5
    sdf_range: [-2,2]
    depth_range: [1.2,3.8]
    importance: true

loss_weight:
    render: 10
    shape_silh: 3
    ray_intsc: 1
    ray_free: 0.1
    eikonal: 1

optim:
    lr: 1.e-4
    test_optim: false
    lr_test: 1.e-2
    iter_test: 500

max_epoch: 28

freq:
    scalar: 100 # iterations
    vis: 200 # iterations
    eval: 10 # epochs
    ckpt: 20 # epochs
    ckpt_latest: 2000 # iterations
