# pretrain SDF-SRN to predict a sphere
_parent_: options/pascal3d/implicit.yaml

group: pretrain
name: pascal3d

latent_std: 1.

impl:
    sdf_range: [-2,2]
    pretrain_radius: 0.5

loss_weight:
    sphere: 1

optim:
    lr: 1.e-4

max_iter: 1000

visdom:

freq:
    scalar: 100 # iterations
    vis: 100000 # iterations
    eval: 1000 # epochs
    ckpt: 5 # epochs
